name: Build React Vite

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Project
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your desired Node.js version
          cache: "npm"

      - name: Run npm
        run: |
          npm install
          npm run build
