name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Project
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Or your desired Node.js version
          cache: "npm"
      - run: npm install
      - run: npm run build
